### ISSUE TITLE
Top speed / BLDC Control optimization

### ISSUE THREAD

**Issue by lalalandrus** [bipropellant/bipropellant-hoverboard-firmware#10]
Is it possible to include the field weakening code from https://github.com/larsmm/hoverboard-firmware-hack-bbcar to increase the top speed of the hoverboard. 

Because this projects re-integrates the sensors, it can be used in conjunction with the hoverboard carts and achieve a high top speed.

**Comment by btsimonh** [comment]
looks like weakl and weakr are already there; we'd just need the code to set them....
Then I guess you could use a sensor angle as an accelerator pedal!
Testing would be an issue; the three of us are 'low speed' applications.  With a suitable build, it could be 'road tested' unmanned and wifi controlled, but would exceed the speed limit on my road :).
PRs welcome.

**Comment by p-h-a-i-l** [comment]
Pull requests are very welcome 😋

**Comment by lalalandrus** [comment]
What if I told you I can help convert all your wheels into 10inch. I can write a tutorial and you can do balance at high speed :)

**Comment by lalalandrus** [comment]
What if I told you I can help convert all your wheels into 10inch. I can write a tutorial and you can do balance at high speed :)
https://imgur.com/a/8RkTix0

**Comment by btsimonh** [comment]
haha!  I did think about if we could put something around the wheels - or fit 'snow chains' for operation on grass :).

**Comment by lalalandrus** [comment]
This widens the base and the stability increases substantially

**Comment by btsimonh** [comment]
I can see why you want to go faster that your standard hoverboard; with standard hoverboard control :).  May need to upgrade the way the wheels are attached, and check the bearings occasionally.  But also I guess that your weight is not necessarily directly over the wheels, so the bearings may be under a slightly lighter load.

**Comment by lalalandrus** [comment]
I tried compiling it through platformIO and programming firmware.bin but the board is now unresponsive. Is there anything special I need to do?

![Untitled](https://user-images.githubusercontent.com/1332079/57965512-0d314280-78fa-11e9-97db-bcbdc95a0d37.png)

**Comment by btsimonh** [comment]
you are in hoverboard mode?
Is it a real STM32 or a GD32?
For my GD32 based board, the serial rates to the sensor boards did not match that reported by others...  
```
  #define USART2_BAUD     52177    // control via usart from GD32 based sensor boards @52177 baud
  #define USART3_BAUD     52177    // control via usart from GD32 based sensor boards @52177 baud
//#define USART2_BAUD     26300    // reported baudrate for other sensor boards?
//#define USART3_BAUD     26300    // reported baudrate for other sensor boards?
```
To my knowledge, I am the only person who has run this with sensor boards (so they have only been tested with my GD32 based YST board setup).
Did you get a serial connection to it?  - that's probably the place to start....
And get a 'scope on the serial out of the sensor boards and estimate the baud rate - i think they pump data out constantly from power on.

good luck!

**Comment by lalalandrus** [comment]
My main board is a real ST32 and the sensors are GD32. I will scope it and read the serial port. Right now it is just stuck always on doing nothing.

**Comment by btsimonh** [comment]
first time i programmed mine from the new repo, my flash played up; never got to the bottom of it, but now seems ok.  if Hoverboard mode is disabled in flash, then it will not do hoverboard functions.
You have no lights, and no response to sensor foot pads?  try 'double tap' on the footpads (two activations in one second).

**Comment by lalalandrus** [comment]
Abusing the power off pin I tracked it down to init flash. I haven't had a chance to test but I am suspecting that you are not really saving a flash area. It is not defined in the linker or the flash area.c. Also I don't understand how you got 0x8000000+62*2048 in flash access but you want 0x800c000 (but not declared) in flash area.

**Comment by btsimonh** [comment]
the flash was my imaginative from scratch implementation, just stole some code from elsewhere. :).
I think (a little time ago now) I intended it to beyond the end of any code, and if flash magic not matched, to re-write.  Using the serial, you have to write the correct value to the flash magic to save to the flash....  but it seemed to work as i diagnosed it a few weeks ago.
The flash area should be a segment in the linker file: (but see below... this is irrelevant)...
https://github.com/bipropellant/hoverboard-firmware/blob/master/STM32F103RCTx_FLASH.ld
```
  /* create a section in flash which is aligned on a page boundary, don't really care where. */
  .myFlashSection :
  {
     . = ALIGN(2048);
     *(.myFlashSection)
     *(.myFlashSection*)
     . = ALIGN(2048);
  } >FLASH
```
the referenced:
`const uint8_t __attribute__((section (".myFlashSection"))) flash_data_inimage[FLASH_LEN]  __attribute__ ((aligned (2048))) = {
`

but.... you are right, in flash_access.c:
`volatile uint8_t *flash_data = (uint8_t *) 0x08000000 + 62*2048;`

... so we don't use the 'inimage' variable.... and we rely on 0x08000000 + 62*2048 being beyond the end of our code.
best double check you have this amount of flash in STM32?

s

**Comment by lalalandrus** [comment]
I found the issues and cleaned up the section defines + rearranged inits until I got the code working. I am now stuck with both "power" led's being red but at least it is not crashing. The hoverboard is turning off via button but not via the 60s timeout, this might be my next clue. Ill send the pull requests for the other stuff.\

**Comment by btsimonh** [comment]
power leds mean you have coms to sensor boards (i believe).
if HB mode is active, you should get dull green for one foot, bright green for two, and motors should try to make HB level in red.
If not, double tap should enable HB mode.
did you get serial to it yet?

**Comment by lalalandrus** [comment]
Serial is the correct baud. But I suspect there is a bug there sensor board uart died because I can't see any serial from the main board to the sensors when it should be constantly sending light info

**Comment by btsimonh** [comment]
you have software serial for diags?

**Comment by lalalandrus** [comment]
After the power on message nothing else pops up

**Comment by btsimonh** [comment]
did you send unlockASCII? - but it should tell you to do this on the serial.....
To get it to output debug you may need to enable Ascii and 'EC<cr>'.
then to dump flash 'Fa'<cr>.
To commit any changes to flash 'Fm1234<cr>'.

**Comment by lalalandrus** [comment]
while i have found a few quirks and optimizations i think the issue is that the type of sensor boards i have are sending the data immediately one after another and the mainboard code that i have is unable to find the SOF and the bit alignment is wrong. the 9 bit serial i am sending to the led is working

**Comment by btsimonh** [comment]
check the new 'combined' branches...  I believe the 0x1xx is the first thing received in each message.
For lights, I had to move 'color' to the front.
For receive, I now wait for 0x1xx, and then put that and up to  bytes into a buffer.  on the 10th byte, I coy the buffer to the used structure, and process it.

**Comment by lalalandrus** [comment]
i already moved colour to the front in sensorcomms.h
i think your yst boards have more info, the standard sensor boards only have 6 bytes including the header mem copy would be dangerous in this instance and direct variable definition would yield better cross compatibility should your strut packing change

**Comment by lalalandrus** [comment]
i finally got my hoverboard working but it seems to go into some emergency stop mode once i hit 3km/h

any thoughts?

**Comment by btsimonh** [comment]
yes, you are right; I have 10 byte frames from the sensor board.  Better not implement anything important based on Roll or acceleration!

A thought on baud rate:
1/ they want to have a constant FRAME RATE.  
2/ My frames are 10 words (11 bits each?) at 52177 -> frame interval 2.1ms
3/ Your frames are 6 words (11 bits each?) at 26315 -> frame interval 2.5ms
4/ @EmanuelFeru is at ~32100  -> maybe he has 7 words?

ref stop mode.  Does it bleep?
It could be batt, temp, or timeout.  Power off timer should not activate if you have motion.
It could be voltage detect calibration, or temp calibration?
Let us know after a charge :).

**Comment by TomTinkering** [comment]
Hey guys, I saw this comment on the "NiklasFauth" thread for Sinusoidal control of PMSM;

"@lalalandrusVector control like FOC, indeed would be nice, however I think we will reach the STM32F1 Series computational limitations, since we need to run the algorithm at 100 kHz and plus some additional code for balancing controller or other calculations. STM32F4 series are much more capable but they are not in the hoverboard."

I just ordered [this](https://www.ebay.nl/itm/Circuit-Board-Main-Motherboard-For-6-5-10inch-Balance-Scooter-Replacement-Part/143217214985) hoverboard control board, and it comes with an F4 by GigaDevices. It also includes Mosfet drivers rather than a custom discrete implementation with BJT's for the motor drives. 

Looking on Ebay I see a lot more of these boards around, so could it be worth developing for this board instead? I could help out with the base firmware (ADC's, PWM outputs etc.), but I don't know much about FOC. I do have an updated [schematic](http://vocke.tv/lib/exe/fetch.php?media=20190518_hoverboard_sch.pdf) of the board.

**Comment by btsimonh** [comment]
it's probably the same as my YST board....  GD32 based, double the CPU power (not sure what clock I'm running with the firmware though).
there is some info on my board herE:
https://github.com/btsimonh/hoverboard-firmware-hack/tree/newprotocol/otherboards/YST-6.5-10-PCBA-10
and some pics in folder above.
If it is the same, it's got some nice spare pins, not too difficult to access....
Confirm?

**Comment by TomTinkering** [comment]
Yes, it is an YST board, but I think the next generation, as it features a GD32F403 instead of 103

**Comment by EmanuelFeru** [comment]
> 
> 
> Yes, it is an YST board, but I think the next generation, as it features a GD32F403 instead of 103.
> 
> I will be using this board in the coming weeks for a project, and was planning to port the NiklasFauth firmware for it. Of course it would be even better if FOC would also be possible.

Cortex®-M4 Core @ 168 MHz​ ... nice! The board is cheap actually. I hope the interfaces are the same. Let us know if you the firmware runs on it. So, no issues with the configuration of port, timers, etc.

**Comment by EmanuelFeru** [comment]
By the way, is someone of you using the [STM-STUDIO-STM32](https://www.st.com/en/development-tools/stm-studio-stm32.html) for vizualization and debugging? 
I tryied it and it worked nicely first times but after few usages it cannot read the variables any more from the "firmware.elf" file. I wonder if you had the same issue. 
I would like to use it because if very nice for Visualization and online tuning.

**Comment by TomTinkering** [comment]
> > Yes, it is an YST board, but I think the next generation, as it features a GD32F403 instead of 103.
> > I will be using this board in the coming weeks for a project, and was planning to port the NiklasFauth firmware for it. Of course it would be even better if FOC would also be possible.
> 
> Cortex®-M4 Core @ 168 MHz​ ... nice! The board is cheap actually. I hope the interfaces are the same. Let us know if the firmware runs on it. So, no issues with the configuration of ports, timers, etc.

The interfaces are largely the same, but not all. Also the DC current measurement is removed (so only phase current/voltage). The firmware will likely not run, but I will work on that the coming weeks. I will let you know when I get Niklas's firmware running, then maybe we can continue from there

**Comment by lalalandrus** [comment]
we have a LOT of flash, with look up tables and fixed point math we might be able to achieve pretty good motor control. 

if full vector control cant be achieved just lead / lag angle control might be close enough to be versatile to both the high speed and low speed applications

**Comment by EmanuelFeru** [comment]
Just to tease you a bit :D check this out
https://drive.google.com/file/d/1vC_kEkp2LE2lAaMCJcmK4z2m3jrPUoBD/view

1st half of the video = Commutation method
2nd half of the video = Sinusoidal 3rd armonic

**Comment by btsimonh** [comment]
ok, when can we implement? :)  is this yours?  or what git?  !!!!  can it do slowwwwwww?

**Comment by EmanuelFeru** [comment]
My pure implementation... fresh new :)

**Comment by EmanuelFeru** [comment]
I use Commutation method to start the motor.  I estimate the rotor position based on Hall sensors, so I need a spinning motor.
It spins slowly as well. How slow do you need?

**Comment by btsimonh** [comment]
Really looking forward to it, because sinusoidal had me really flumuxed for quite a few days...  with no viable result...

**Comment by btsimonh** [comment]
want fine control of position.....  for very slow - inspiration is here:
https://hackaday.com/2015/04/20/driving-a-brushless-dc-motor-sloooooooowly/

think robot rather than moving vehicle....

**Comment by EmanuelFeru** [comment]
You can here a small wobble sound in the video... that is because the wheel is not perfect straight. It is also visible in the video. My hoverboard is a used one... I said if I am going to break it at least I should use a used one :)

**Comment by EmanuelFeru** [comment]
> want fine control of position..... for very slow - inspiration is here:
> https://hackaday.com/2015/04/20/driving-a-brushless-dc-motor-sloooooooowly/
> 
> think robot rather than moving vehicle....

When I will publish you can try to see if it is sufficient for what you need. If not, we see what can we do.
One thing, also the original firmware starts the first spin with Commutation method, you can hear the tick tick noise, then it switches I guess to also a sinusoidal method. Did notice it?

**Comment by btsimonh** [comment]
hmm...  I do get ticks.  But not really related to starting.  I'll try to understand your code when I see it :).

**Comment by lalalandrus** [comment]
that sent chills down my spine...
i use my hoverboard for this
![image](https://user-images.githubusercontent.com/1332079/58288208-c31be700-7d67-11e9-92f5-2985b85e6013.png)

but with big tires https://imgur.com/a/8RkTix0 

i ride the hoverboard everyday at work and i was testing it on a ridge to think about how they do the commutation before your comment and yes there is a tick.

**Comment by btsimonh** [comment]
My clicks are definitely bad sensor reads:
```
"colour 0 c -> 4 (51)"
5/23/2019, 11:28:55 PMnode: 9bab8706.92f058
"SensorOK -> 0 in unprocessed poll"
5/23/2019, 11:28:56 PMnode: 9bab8706.92f058
"colour 0 4 -> 8 (52)"
5/23/2019, 11:28:56 PMnode: 9bab8706.92f058
"colour 1 c -> 8 (53)"
5/23/2019, 11:28:58 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:28:58 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:08 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:11 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:14 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:35 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:35 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:46 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:47 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:47 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:49 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:50 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:53 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:55 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
5/23/2019, 11:29:56 PMnode: 9bab8706.92f058
"sensor data not 55 or AA"
```

**Comment by p-h-a-i-l** [comment]
> Just to tease you a bit :D check this out
> https://drive.google.com/file/d/1vC_kEkp2LE2lAaMCJcmK4z2m3jrPUoBD/view
> 
> 1st half of the video = Commutation method
> 2nd half of the video = Sinusoidal 3rd armonic
> 
> * Pay attention on the noise level

What a teaser!!! We NEED this 😀

**Comment by EmanuelFeru** [comment]
I am happy that you like it :-) I will do a bit more testing then I will share it with you.

@TomTinkering I saw in the presentation of Niklas that you built a GUI for tuning parameters [link](https://github.com/TomTinkering/CfgBus-GUI). What do I need to do to use it for hoverboard parameters tuning?

**Comment by TomTinkering** [comment]
> @TomTinkering I saw in the presentation of Niklas that you built a GUI for tuning parameters [link](https://github.com/TomTinkering/CfgBus-GUI). What do I need to do to use it for hoverboard parameters tuning?

Yes, it is a bit involved unfortunately. There link you shared is a Qt5 gui that talks to the hoverboard using a serial port. On the hoverboard side you need to implement the client. It is based on modbus, and works with any modbus RTU tool. The tunable parameters need to be globals in the hoverboard code. You can dig through the code [here](https://github.com/TomTinkering/hoverboard-firmware-hack). It is some work unfortunately. If you let me know which parameters should be tunable, I might be able to port it to your project this weekend if you want to try it.

**Comment by EmanuelFeru** [comment]
> If you let me know which parameters should be tunable, I might be able to port it to your project this weekend if you want to try it.

Thanks for the info. I would like to access the parameters for the new motor control that I made to do some calibration. These are new parameters compared to the Niklas repo.
Ideally, I was looking for a tool that can access the memory locations by loading the description file "firmware.elf". This file is created when building the code (I am using VS code).

**Comment by lalalandrus** [comment]
There is a serial debug that will allow you to read and write flash that is implemented already.

**Comment by btsimonh** [comment]
@EmanuelFeru - take a look at the hbprotocol wiki.
it's a little out of date - the parameter table has changed a bit (for the better).  (changes welcome!)

but basically, add your new params to 
https://github.com/bipropellant/hoverboard-firmware/blob/master/inc/flashcontent.h
with suitable defaults.

then add lines in 
https://github.com/bipropellant/hbprotocol/blob/master/protocol.c
near
`    { 0xA0, "hoverboard enable",       "he",  UI_SHORT, &FlashContent.HoverboardEnable,       sizeof(short),             PARAM_RW, fn_preWriteClear } // e.g. 20
`
to reference your new variables:
give them a human name, chars used to access them.  Only UI_SHORT is supported at the moment.
Choose a new number (maybe start at 0xB0?) - the number is used in the machine protocol to read.write.

then, e.g. working with 'hoverboard enable' as an example:
to read, use:
Fhe<\n>
to set to 1
Fhe1\n

this will SET the variable in MEMORY.
To commit the memory to flash, use 
Fm1234<\n>

First firmware update with new variables, use
Fi<\n>
to initialise.

(positive decimals only at the moment, pull requests welcome...).
br,
s

**Comment by EmanuelFeru** [comment]
Hello everyone @btsimonh @lalalandrus @p-h-a-i-l @TomTinkering,

First release of the new BLDC control is committed here:
https://github.com/EmanuelFeru/hoverboard-firmware-hack

Feel free to give it a try and let me know what you think about it.
@btsimonh What do you say of integrating this new control into your FW to restore the hoverboard functionality? It should now be very close to the original FW, if not better.

@lalalandrus  By the way... the Phase advance or Field weakening is crazy! it can reach really high speeds.

**Comment by lalalandrus** [comment]
@EmanuelFeru i am excited, i will start trying to integrate the baseline into my fork now since i am bored at work. @btsimonh can make it pretty

**Comment by EmanuelFeru** [comment]
Nice to do something fun like this at work, I agree :) I am exited too, for your feedback. 

> wow, it looks like you went through the trouble of modeling the motor parameters too!
I modeled the parameters of the motors roughly. The Simulink model is more for functional development. So, it is not exact with reality, but I fined tuned the controller on the real motor.

**Comment by lalalandrus** [comment]
@EmanuelFeru you should test out the newest commits, the calibration makes the hoverboard functions really slick now, there is a 'pwm = anlge/3' which should be changed as it is a bit sluggish right now maybe a /2 is suffice.

**Comment by EmanuelFeru** [comment]
Do you mean this repo https://github.com/bipropellant/bipropellant-hoverboard-firmware?
Because I really want to try this repo to "feel" the hoverboard functionality. Is it now working with STM32 boards?

**Comment by lalalandrus** [comment]
yes this current repo, it is working with my stm board reliably but you might need to fiddle with your baud rate settings, your "should" be a 6word sensor as per the config.h file

**Comment by EmanuelFeru** [comment]
I am not sure if mine is 6 word sensor. When I did the hack on the serial I was sending the data below. The motors were listening to my commands.

`		// Send data
		dataL[0] = 256;
		dataL[1] = uL & 0xFF;
		dataL[2] = (uL >> 8) & 0xFF;
		dataL[3] = uL & 0xFF;
		dataL[4] = (uL >> 8) & 0xFF;
		dataL[5] = 85;
		dataL[6] = 82;
		dataL[7] = 82;	
		
		dataR[0] = 256;
		dataR[1] = uR & 0xFF;
		dataR[2] = (uR >> 8) & 0xFF;
		dataR[3] = uR & 0xFF;
		dataR[4] = (uR >> 8) & 0xFF;
		dataR[5] = 85;
		dataR[6] = 82;
		dataR[7] = 82;
		
		if (stop)
		{
			dataL[5] = 170;
			dataR[5] = 170;
		}		
		
		HAL_UART_Transmit_IT(&huart1, (uint8_t *)dataL, n);
		
		HAL_UART_Transmit_IT(&huart3, (uint8_t *)dataR, n);

`

**Comment by lalalandrus** [comment]
i believe the way the firmware is written now, if you select 6 word with the right baud rate, it will still work even if it has too much data as it will just ignore it until the next new frame. 

i have integrated your code into my branch, will need to do some testing before a PR but @EmanuelFeru and @btsimonh can test from my branch the new motor control

https://github.com/lalalandrus/hoverboard-firmware

**Comment by p-h-a-i-l** [comment]
Got it running :+1: 
very nice :)

(had to add the new .c files to the makefile, but its working)

Some strange things: Melody on first boot was very slow, motors start after 5 minutes waiting, sometimes only one wheel.

**Comment by p-h-a-i-l** [comment]
https://wolke.hacknology.de/index.php/s/4KyrzZtR6YeAbTF

**Comment by lalalandrus** [comment]
@p-h-a-i-l that is quite the setup you have there

**Comment by lalalandrus** [comment]
@p-h-a-i-l i think @EmanuelFeru has changed the irq behaviour in his new code

**Comment by lalalandrus** [comment]
@p-h-a-i-l i think @EmanuelFeru has changed the irq behaviour in his new code, could be causing the new issues

EDIT: I have hit a wall. Calling BLDC_controller_step() in the DMA IRQ of BLDC.C causes the hoverboard to crash.

**Comment by EmanuelFeru** [comment]
> Some strange things: Melody on first boot was very slow, motors start after 5 minutes waiting, sometimes only one wheel.

@p-h-a-i-l  Few things that come into my mind:
1. Do you have any other additional code running together with my commit? It might be that computationally we are close to the limit, so we might need to slow down a bit the triggering of the interrupt routine.
3. I use platformio in VS Code to build and flash (under Windows). Could that make a difference?...  I am not sure.
2. I committed my "firmware.bin". Can you flash this file and try? Because for me it works perfectly and the beep at the begging is fast (normal melody).

**Comment by lalalandrus** [comment]
i am running code that is as close to the baseline bipropellant for integration, it does have a little bit more functionality than what you have. i am trying to merge the two projects together
i program the hoverboard in the same way using platformIO
i have disabled irqs right when it enters the dma function and it still does not want to play nice
i cannot use pots as i dont have one to test with

**Comment by EmanuelFeru** [comment]
Can you set the calibratable CTRL_TYP_SEL = 0 (commutation method) in config.h? At least to check that it runs and is not something else.

**Comment by lalalandrus** [comment]
Woot getting somewhere.  CTRL_TYP_SEL = 0 works but direction is reversed and it is very twitchy.

**Comment by EmanuelFeru** [comment]
> Woot getting somewhere. CTRL_TYP_SEL = 0 works but direction is reversed and it is very twitchy. This is based on the code as it is checked into my repo.

- Yes, I think I might reverse the direction because I had to make it consident between all methods, I think you can readjust with settings INVERT_R_DIRECTION and INVERT_L_DIRECTION
- If it still works twitchy, I think it has to do with how oftent the interrupt is triggered. I guess in your case is triggered very often, so you get some over-runs (even with the commutation method). So is not able to finish the calculation and there is already a new interrupt being triggered.

To be honest, I did not understand how to manipulate the triggering of the interrupt DMA1_Channel1_IRQHandler() and where is it done. It says in a comment that should trigger at 100 kHz (I think in my case triggers a bit at a lower rate). I would like to know this rate for my speed calculation. Do you know how to manipulate the interrupt triggering? That could fix the twitchy behavior.

**Comment by btsimonh** [comment]
@EmanuelFeru -
I'll await @p-h-a-i-l or @lalalandrus 's PRs :).  Really looking forward to it...

General comments:
I was thinking about instrumenting performance better; STM32 provides a way of reading CPU cycles, so we could instrument the major routines in the code, and then we'd know how close to the edge we were.  Something like counting CPU cycles in main loop (now pretty reliable 5000us), and comparing with averaged BLDC & Hall interrupt routine cycles.  I started this, but then abandoned due to easier higher priorities :).
In a VERY quick scan of the generated code, there are a lot of functions in which are fairly small - if someone has experience with 'inline', the the matlab model could be modified to output with the required markup, and this may increase the code efficiency?  Either that or as #defines into a header file.  I like the separation the functions give us....

p.s.
```
	dataR[6] = 82;
	dataR[7] = 82;
```
on my board, I believe this is a duplicated acceleration value.
I have two more bytes:
```
  unsigned char Accelleration;
  unsigned char Accelleration_duplicate;
  short Roll;
```
Roll is the angle caused by lifting one end of the board.

Ref this repo:
As @lalalandrus stated, if you setup for 6word, it will work fine.  It will also work setup for 10word....  
6word - read complete will trigger on the 6th 9 bit word
10word - read complete will trigger from the next 0x1xx word.
Wire yourself a software serial connection, and flash the firmware as-is, try the hoverboard (& feel the grind!).  Then implement or wait for a completed PR of your implementation, and let's see a better result!
We can easily add modification of rtP.z_ctrlTypSel from the protcol(s) for testing the 4 different methods from a 'feel' perspective :).

**Comment by lalalandrus** [comment]
well until i root out why anything other than commutation isnt working, no PR will be happening any time soon. i will have to find a way to see if the overrun is happening even on the 0 case but it is getting late here on the west coast of NA and will have to wait another day.

**Comment by EmanuelFeru** [comment]
> I was thinking about instrumenting performance better; STM32 provides a way of reading CPU cycles, so we could instrument the major routines in the code, and then we'd know how close to the edge we were. Something like counting CPU cycles in main loop (now pretty reliable 5000us), and comparing with averaged BLDC & Hall interrupt routine cycles. I started this, but then abandoned due to easier higher priorities :).
> In a VERY quick scan of the generated code, there are a lot of functions in which are fairly small - if someone has experience with 'inline', the the matlab model could be modified to output with the required markup, and this may increase the code efficiency? Either that or as #defines into a header file. I like the separation the functions give us....
@btsimonh 
- I will look a bit into more detail how to optimize the generated code. Are #defines constructions more efficient? However, do you know what is triggering the DMA1_Channel1_IRQHandler()?
- Thanks for the info on the hoverboard functionality, I will give it a try tonight ;)

**Comment by btsimonh** [comment]
> EDIT: Ideally, I would like to have this interrupt DMA1_Channel1_IRQHandler() triggered by a timer, so we can easily manipulate it's frequency.

I believe it is the ADC read DMA timer, initialised in setup.c by MX_ADC1_Init().
We're short on timers, especially with software serial :(.  I had to do a bit of juggling to get that working.
I don't know what controls the periodicity of the DMA interrupt - but I'm guessing slowing it down should not cause us any issues with ADC or the data we read..., - note we'd also need to change some constants in the hall interrupt code (which also reads speeds!).

@lalalandrus - start of my day here - have to try to earn some money, but will be looking later :)

**Comment by lalalandrus** [comment]
function calls cause instruction jumps (usually) where defines are duplicated into code always

**Comment by AntumArk** [comment]
To reduce ADC DMA speed,you need to change sampling time.
https://github.com/bipropellant/bipropellant-hoverboard-firmware/blob/9b913c315debcded13eda893997dcdcc1ef07425/src/setup.c#L613

**Comment by EmanuelFeru** [comment]
> 
> 
> To reduce ADC DMA speed,you need to change sampling time.
> 
> https://github.com/bipropellant/bipropellant-hoverboard-firmware/blob/9b913c315debcded13eda893997dcdcc1ef07425/src/setup.c#L613

Awesome. So these are the options:
`#define ADC_SAMPLETIME_1CYCLE_5 	/*!< Sampling time 1.5 ADC clock cycle */
#define ADC_SAMPLETIME_7CYCLES_5  	/*!< Sampling time 7.5 ADC clock cycles */
#define ADC_SAMPLETIME_13CYCLES_5   	/*!< Sampling time 13.5 ADC clock cycles */
#define ADC_SAMPLETIME_28CYCLES_5     	/*!< Sampling time 28.5 ADC clock cycles */
#define ADC_SAMPLETIME_41CYCLES_5     	/*!< Sampling time 41.5 ADC clock cycles */
#define ADC_SAMPLETIME_55CYCLES_5      	/*!< Sampling time 55.5 ADC clock cycles */
#define ADC_SAMPLETIME_71CYCLES_5     	/*!< Sampling time 71.5 ADC clock cycles */
#define ADC_SAMPLETIME_239CYCLES_5  	/*!< Sampling time 239.5 ADC clock cycles */`

They can be found in stm32f1xx_hal_adc.c
I will try tonight different settings to see what is the effect.

**Comment by btsimonh** [comment]
hmm..  so...  
the ADC is in scan mode?  and we're triggering DMA interrupt at 5 longs read?
does that mean that we'd add up all the sample times, and that would give us the DMA interrupt period?
And that we can adjust each sample time to affect the interval, and that we *could* add ADC channels to extend the interval?
I did not pay much attention to this bit of the code; just assumed the comments to be right; but the bldc.c comment states 8 channels, and we seem to be running 5....  so maybe it need a review anyway!
p.s. aside - main loop timing now depends on the rate of this DMA interrupt!!!!

**Comment by EmanuelFeru** [comment]
I have an idea on how to get the sapling rate of DMA1_Channel1_IRQHandler() ... the hard way :)
Just toggle the LED pin inside the interrupt and measure the period between pulse using an oscilloscope. I will try that.

**Comment by p-h-a-i-l** [comment]
> 1. Do you have any other additional code running together with my commit? It might be that computationally we are close to the limit, so we might need to slow down a bit the triggering of the interrupt routine.

No, this was just your code, only modification was a static speed and steer value.

> 2. I use platformio in VS Code to build and flash (under Windows). Could that make a difference?...  I am not sure.

Ah, didnt't notice, so it wasn't even necessary for me to fire up the old make environment ;)

> 3. I committed my "firmware.bin". Can you flash this file and try? Because for me it works perfectly and the beep at the begging is fast (normal melody).

I can try earliest tomorrow evening, but I have the feeling that until then the code will have progressed a liitle ;) Keep up the good work!

@btsimonh Unfortunately I don't have time to do the merge, too much other unfinished business. We have to keep our hopes on @lalalandrus and @EmanuelFeru . I'll try to support and test when possible!

**Comment by EmanuelFeru** [comment]
@p-h-a-i-l  thanks for the info. What type of microcontroller do you have? I have an [STM32F103RCT6](https://www.ebay.com/itm/1PCS-5PCS-STM32F103RCT6-LQFP-64-STM32F103RCT6TR-STM32F103RCT-MCU-ARM-ST-IC/183647636767?ssPageName=STRK%3AMEBIDX%3AIT&var=691112271463&_trksid=p2060353.m2749.l2649), that I bought from ebay.

Maybe you can also give a try of modifying the "sConfig.SamplingTime" in setup.c as described in a post above. I will do the same to check the behavior... we need to get to the bottom of this :D :)

**Comment by EmanuelFeru** [comment]
I tested different settings for the DMA interrupt:
 
 sConfig.SamplingTime = ADC_SAMPLETIME_1CYCLE_5;                   Interrupt period: ~70us
 sConfig.SamplingTime = ADC_SAMPLETIME_7CYCLES_5; (default)   Interrupt period: ~70us
 sConfig.SamplingTime = ADC_SAMPLETIME_71CYCLES_5;               Interrupt period: ~70us
 sConfig.SamplingTime = ADC_SAMPLETIME_239CYCLES_5;             Interrupt period: ~125us

In conclusion:
70us   --> ~14 kHz
125us --> ~  8 kHz

So I am quite far from the 100 kHz stated in the comment. Could that be the reason that it runs for me and not for you? @p-h-a-i-l Can you check your period with the LED method?

Strange part is that only with the ADC_SAMPLETIME_239CYCLES_5 the Interrupt period increases, for the rest is the same interrupt period.

Positive: On my board, the sinusoidal control works with all of them.

**Comment by lalalandrus** [comment]
I never liked that interrupt routine as it did look too clunky. However could we modify your code to run slower say 32khz since the max pwm is 16khz.

**Comment by btsimonh** [comment]
I wonder how different this is on different CPUs.  i.e. is one 'cycle' of ADC the same on all, or do they run at different rates on GD vs STM?
and ha ha - my main loop is reliant on the 100khz - so I'll add to the reported diags the tick ms time as well as the us (from DMA interrupt) time :).  it's probably completely wrong....

**Comment by EmanuelFeru** [comment]
That would be ideal.
For that we need a timer interrupt, separate from the DMA interrupt. My code does not depend on the interrupt. We can place it in another function. I have to check what timer can we use and I need the settings for the timer...  I am not very skilled in setting the timers, prescale, etc. Do you know how to do it?

**Comment by lalalandrus** [comment]
Also @emanuelferu did you measure your original code to confirm that the cpu is capable of 100khz with all that calculation ?

**Comment by EmanuelFeru** [comment]
No, I did not measure the original code. I will do it right now :)

**Comment by btsimonh** [comment]
i think with software serial, we may be out of timers.   Need to check.

**Comment by EmanuelFeru** [comment]
Original code: exactly the same period (as in the picture).
So,  guess my ADCs are very slow then.

**Comment by lalalandrus** [comment]
Well if it is exact tsoemthing else is firing that interrupt at a predetermined rate. Also it means something else is causing it to crash or misbehave. @btsimonh maybe we can delete the software serial somehow...

**Comment by EmanuelFeru** [comment]
@lalalandrus, just asking what is the purpose of Software serial? Because in hoverboard mode, I only see the need of Software serial for debugging purposes. Or is there something else that I miss?

**Comment by btsimonh** [comment]
haha.  because I want my cake and eat it.
Yes debugging.
But also, I want the same binary to support my robotic activities :).

**Comment by EmanuelFeru** [comment]
haha, ok, ok

**Comment by btsimonh** [comment]
ahah...  actually, main timing is done from hall timer.  It's read in the DMA interrupt, because I thought that's the fastest thing we have going.  But the value is the hall timer value, which is constant.

**Comment by EmanuelFeru** [comment]
What is then the hall timer value? Is this the 16 kHz I read and not changing?

**Comment by btsimonh** [comment]
the hall timer runs at 100khz (if using this repo!).
We dont use the interrupt from the timer, only the timer value..
The timer value is used in a hall level detect interrupt set to go off on hall input change, when the timer is read to estimate speed, etc.
So...  if you need TIME in your calculations, it's a good one.

p.s. about to measure DMA interrupt rate via software.

**Comment by lalalandrus** [comment]
thats really confusing. we should disable all hall input level interrupts since his code doesnt need it and use exclusively the timer interrupt (we shouldnt call it hall anymore as it doesnt drive it) and then move everything that is uneeded into another process

**Comment by btsimonh** [comment]
ok, measurements:
Main loop interval_us 5000; lates 3, processing_us 465, interval by tick 5, bldc freq 16055

- so
this is:
main loop measured using hall timer -> 5000us average.
main loop measure using hal_tick -> 4 or 5 ms.
bldc freq mesaured by counting interrupts during hal_delay(200) at startup.
(lates is number of main loops where time was > 5000us, cause by serial_send_wait by '?' in ascii protocol).

so in THIS repo, we get a bldc DMA interrupt rate of ~16khz.  The comment is completely wrong!.

@lalalandrus - the hall interrupt is important - although the DRIVE does not require it, accurate position does - we need to know EVERY time the hall sensors change in order to measure our position accurately.  This is something that was missing from the initial repo....  the 'hall timer' is purely to give us an accurate time when the interrupt goes off to tell us a hall line has changed.

**Comment by lalalandrus** [comment]
@btsimonh his motor controller is a state estimator running at 100khz which would actually give you pretty good position data. i would recommend you think about if it can suit your needs as the hall effect only gives you roughly 40 degree resolution which is pretty poor.

**Comment by EmanuelFeru** [comment]
yes, @lalalandrus , I do output also the electrical angle (also between hall changes), which is quite a good estimate, especially when motor is spinning.
For my understand, where do you use the position estimation in your algorithm?

**Comment by btsimonh** [comment]
it's accurate counters available to the protocol.  So, no estimation, we know where the wheels are to within 6mm.... (and so, assuming no slip between the wheels and the surface, we have position accuracy).

**Comment by btsimonh** [comment]
p.s. the 100khz timer could interrupt at a known rate and we can still have the accurate time.... with a little care.  So we could change the bldc interrupt over to a timer source.....

**Comment by btsimonh** [comment]
@lalalandrus - how is your repo?  did you get sinusoidal working?

**Comment by lalalandrus** [comment]
The way it works with discrete control is we need to fire are set intervals and not change it. Having accurate time is not the same as computing at set intervals. The estimator is not what you think it is only doing an estimate. It can still give you the min 6mm accuracy but in fact you could gain some reduction sub 6mm

**Comment by lalalandrus** [comment]
No it crashes still and I am at work without anything to test.

**Comment by btsimonh** [comment]
ok, so about to pull your master and take a look.....

**Comment by AntumArk** [comment]
> I tested different settings for the DMA interrupt:
> 
> sConfig.SamplingTime = ADC_SAMPLETIME_1CYCLE_5; Interrupt period: ~60us
> sConfig.SamplingTime = ADC_SAMPLETIME_7CYCLES_5; (default) Interrupt period: ~60us
> sConfig.SamplingTime = ADC_SAMPLETIME_55CYCLES_5; Interrupt period: ~60us
> sConfig.SamplingTime = ADC_SAMPLETIME_71CYCLES_5; Interrupt period: ~60us
> sConfig.SamplingTime = ADC_SAMPLETIME_239CYCLES_5; Interrupt period: ~125us
> 
> ![Picture1](https://user-images.githubusercontent.com/24780745/58573345-d20a0a00-823d-11e9-9228-3e13db6e65ed.jpg)
> 
> In conclusion:
> 60us --> ~16 kHz
> 125us --> ~ 8 kHz
> 
> So I am quite far from the 100 kHz stated in the comment. Could that be the reason that it runs for me and not for you? @p-h-a-i-l Can you check your period with the LED method?
> You can comment out the line "BLDC_controller_step();" in bldc.c to loose the calculations.
> 
> Strange part is that only with the ADC_SAMPLETIME_239CYCLES_5 the Interrupt period increases, for the rest is the same interrupt period.
> @AntumArk, do you have any idea why?
> 
> Positive: On my board, the sinusoidal control works with all of them.

Upon more inspection,  original firmware has 8 Mhz adc clock. And it is triggered by 8th timer
![image](https://user-images.githubusercontent.com/23199497/58584105-2fae4e80-825e-11e9-8cc6-b452cd6e92b7.png) .
**Timer8 config**
![image](https://user-images.githubusercontent.com/23199497/58584480-093ce300-825f-11e9-9f46-2c5288542b3a.png)
**Clock config**
![image](https://user-images.githubusercontent.com/23199497/58584555-312c4680-825f-11e9-9c45-808d68065b88.png)

 It could be that changing PWM frequency may improve results.  
And about 239.5 value - it also reads temperature , so it may add up to longer calculations.

More about ADC DMA - "In using DMA, when the DMA mode is enabled (DMAEN bit set to 1 in the ADC_CFGR register in single ADC mode), a **DMA request is generated after each channel conversion**.
This allows converted data to be transferred from the ADC_DR register to the destination
selected by the software." Source: https://www.st.com/content/ccc/resource/technical/document/application_note/48/64/0d/61/be/65/48/ae/DM00069390.pdf/files/DM00069390.pdf/jcr:content/translations/en.DM00069390.pdf 
page 8.

**Comment by EmanuelFeru** [comment]
@AntumArk useful info. Do you have the original firmware configuration in CubeMX?!

**Comment by AntumArk** [comment]
@EmanuelFeru Yes I do. Although code apart is still buggy on Keil. I haven't tried using it on TrueStudio yet.

**Comment by EmanuelFeru** [comment]
Wow, can you share it? I was looking for it actually.

**Comment by AntumArk** [comment]
@EmanuelFeru Here you go! https://github.com/AntumArk/HoverboardMX . Transfered code is heavily modified only for UART application, so i left it out.

**Comment by btsimonh** [comment]
ok, new drive.
using Iw\n
then w/s
control smooth (had to look at the HB to see th wheels were turning, so quiet).

main timing stats now
Main loop interval_us 5001; lates 3, processing_us 1955, interval by tick 5, bldc freq 16020
(compare to above - we've gone from 400us -> 2ms for processing in main loop -> time stolen by bldc interrupt on GD32 - which has about double the performance of STM32).
Now going to 'get on board' in hoverboard mode - wish me luck!

**Comment by btsimonh** [comment]
angle is reversed! (get on - bang thrown off!)

**Comment by EmanuelFeru** [comment]
@btsimonh Did you get it working?? Good luck!

**Comment by EmanuelFeru** [comment]
Yes, reverse the directions, sorrryyy!

**Comment by btsimonh** [comment]
spot on.  First time.
much quieter.
MUCH more miss-reads from sensors. (bldc interrupt > priority than USART interrupts? -> ticks for me).
So, for you STM32 users, more efficiency needed?  @EmanuelFeru - how is the '#defines' thougths coming on?

**Comment by btsimonh** [comment]
@EmanuelFeru - what does pwml/r mean now?  is it the amount of drive, or a speed demand?

**Comment by AntumArk** [comment]
> spot on. First time.
> much quieter.
> MUCH more miss-reads from sensors. (bldc interrupt > priority than USART interrupts? -> ticks for me).
> So, for you STM32 users, more efficiency needed? @EmanuelFeru - how is the '#defines' thougths coming on?
> (i.e. IT WORKS AS A HOVERBOARD!!!!!! Yeah!!!!)

![image](https://user-images.githubusercontent.com/23199497/58586900-cc73ea80-8264-11e9-968c-179e5de2885c.png)
 **Interrupt priorities aren't actualy set :D**

**Comment by btsimonh** [comment]
p.s. branch https://github.com/bipropellant/bipropellant-hoverboard-firmware/tree/newbldc-btsimonh is what I have right now, *working* on GD32 based board.  have been battling with the 'ticks' for a while, will try setting/raising USART priority, whilst double checking code efficiency.  I'm guessing that the bldc routine won;t suffer too much from being interrupted....

**Comment by btsimonh** [comment]
no.  further check -> NOT sensor misread necessarily.  What it does feel like is a hall 'slip'.  Like it manages to skip a segment, jump to the next.  Maybe it's a low speed artifact (mostly happens when standing upright and balancing - or manipulating the board by hands?).  We don't expect this to work well at low speed, @EmanuelFeru correct?

**Comment by lalalandrus** [comment]
what was the missing link ?

**Comment by btsimonh** [comment]
it happens at high speed too :(.  (pick up a wheel, and rotate board angle, ticks are quite sever, especially when changing speed.)
@lalalandrus - missing link?  just worked first time after merging your repo - check the push for the (small) adjustments - but it's on top of another branch, not on top of main :(.  but nothing which should affect this.

**Comment by lalalandrus** [comment]
weird mine crashes everytime, ill try again tonight

**Comment by EmanuelFeru** [comment]
> spot on. First time.
much quieter.
MUCH more miss-reads from sensors. (bldc interrupt > priority than USART interrupts? -> ticks for me).
So, for you STM32 users, more efficiency needed? @EmanuelFeru - how is the '#defines' thougths coming on?
(i.e. IT WORKS AS A HOVERBOARD!!!!!! Yeah!!!!)

- Nice! I checked today regarding #defines but is not actually possible with current Matlab auto-code generation unfortunately. So, we need to work around it.

> @EmanuelFeru - what does pwml/r mean now? is it the amount of drive, or a speed demand?

- Those mean exactly as before, the pwm left and right. I reused the variables

>  What it does feel like is a hall 'slip'. Like it manages to skip a segment, jump to the next. Maybe it's a low speed artifact (mostly happens when standing upright and balancing - or manipulating the board by hands?). We don't expect this to work well at low speed, @EmanuelFeru correct?

- At low speeds, I still use commutation method so normally it should behave like with the previous BLDC control. Then after it starts moving I switch to Sinusoidal. I do this, because I need a spinning motor to calculate the angle properly. The factory firmware does the same.

**Comment by EmanuelFeru** [comment]
By the way, I just tried your repo and it works on my board as a hoverboard! The controller could be a bit tuned to be more aggressive, but other than that it works.

What I changed is one line (line 43 in config.h, My baud rate is actually 31200 bps):

`// #define SENSOR_BAUD     31200    // reported baudrate for another sensor board (DENVER brand hoverboards) (10 word)`

@lalalandrus @btsimonh maybe you can update this line in the repo?

**Comment by EmanuelFeru** [comment]
@btsimonh Nice job on the hoverboard controller. I would really like to understand the control structure that you use. Maybe when you have time, you can share it.

**Comment by lalalandrus** [comment]
@EmanuelFeru start with my repo unless you want to start from scratch.  :( so many different baud rates....

**Comment by btsimonh** [comment]
do you use platformio?
if so, define a new 'env' for yourself, change the baud there, and PR.  And build from platofrmio env build:
![image](https://user-images.githubusercontent.com/3137332/58588295-3f766480-8257-11e9-901a-7187741d9f3d.png)

Will change the comment.. so you have 8 words? yes?

**Comment by EmanuelFeru** [comment]
> Will change the comment.. so you have 8 words? yes?
No, I used default, so 10 words as I see.

**Comment by btsimonh** [comment]
it would work regardless, just may be better to know the number.  I thought you had acceleration but not roll?  or was that someone else?  or was it just what your were sending,not necessarily what you actually saw from the sensor boards?  (i'll change the comment to 10, but if you find different, you can always issue a PR :) ).

**Comment by EmanuelFeru** [comment]
Ok. I don't know exactly the number of words since I do not have a logic analyzer. I just saw in other places, tried it and it worked.
Funny part is that without those 2 times  "82" at the end the motors stopped listening. I was also puzzled why those numbers at the end. I still don't know why.

**Comment by EmanuelFeru** [comment]
@lalalandrus 

> @EmanuelFeru start with my repo unless you want to start from scratch. :( so many different baud rates....

ok. It is always good to start from something :) Link?

**Comment by btsimonh** [comment]
new measurements:
Main loop interval_us 5000; lates 1, processing_us 1341, interval by tick 5, bldc freq 16005
compare to prev:
Main loop interval_us 5001; lates 3, processing_us 1955, interval by tick 5, bldc freq 16020

1 line change:
`#define static static inline`
near top of BLDC_controller.c
Not a miracle, but a start..... (does not solve ticking.)

**Comment by lalalandrus** [comment]
https://github.com/lalalandrus/hoverboard-firmware

according to @btsimonh it works more or less as is on the GD uC (motor directions reversed)

**Comment by EmanuelFeru** [comment]
@btsimonh I just tried with SENSOR_WORDS 6, 8, and 10. They all work. I confirm.

**Comment by AntumArk** [comment]
> ped listening. I was also puzzled why those numbers at the end. I still don't know why.

Those are END bytes. Fairly ussual for communication protocols. You have Start bytes and End bytes . That is how you can detect a packet.

**Comment by btsimonh** [comment]
haha...  @lalalandrus and I just moved to using them as start bytes !  it make little difference on receipt as the data is very regular and constant.  On send, I just send twice, avoiding issues.

**Comment by lalalandrus** [comment]
UART comms like this x100 is start byte and 82 could be an end byte but no needed in our case. as a someone who makes fiber optic switches i would say start bytes are almost always present and endbytes are only sometimes present

**Comment by AntumArk** [comment]
Well for moving it is best for all packets to be correct. Health is at risk.

**Comment by lalalandrus** [comment]
> it happens at high speed too :(. (pick up a wheel, and rotate board angle, ticks are quite sever, especially when changing speed.)
> @lalalandrus - missing link? just worked first time after merging your repo - check the push for the (small) adjustments - but it's on top of another branch, not on top of main :(. but nothing which should affect this.

it seems your GD32F403 is M4 @ 168M  with zero wait flash execution which would be much much faster than our STM32F104 M3 @ 72M with a one instruction wait state

**Comment by btsimonh** [comment]
:) ref the 0x100, it's definately 0x1xx - the msg SENT to the sensor board uses the low 8 bits for colour....  in the msg received, I've never seen anything but 00 in the lower 8 bits of the word with the 9th bit set....
Just rode the board to the kitchen and back, and it's no worse than with the old BLDC in terms of the missed steps.  Just a lot quieter at speed... :).

@EmanuelFeru - what variable was it you said controlled the expected interval?  & what should I set it to for 16khz?

**Comment by EmanuelFeru** [comment]
@btsimonh According to my measurements, I was running the sinusoidal BLDC control at 16 kHz without problems and down to 8 kHz. So in this range 8kHz - 16 kHz should be fine. I did not test on higher frequencies than 16 kHz.

**Comment by btsimonh** [comment]
@lalalandrus - "the hall effect only gives you roughly 40 degree resolution which is pretty poor."
- look at the wheel construction, one tick of hall == ~6mm - there are many BLDC 'revolutions' per wheel revolution because there are lots of magnets.  I counted 90 identifiable hall positions per rev on my motors....

**Comment by lalalandrus** [comment]
> @lalalandrus - "the hall effect only gives you roughly 40 degree resolution which is pretty poor."
> 
> * look at the wheel construction, one tick of hall == ~6mm - there are many BLDC 'revolutions' per wheel revolution because there are lots of magnets.  I counted 90 identifiable hall positions per rev on my motors....

lol order of magnitide off 4 degrees vs 40 my math is bad

**Comment by btsimonh** [comment]
@EmanuelFeru - so your position estimation does not depend on a time interval, as long as we're within a range?
We could easily test at 8khz on STM32 by only running the BLDC every 2nd interrupt? (please test?)
How fast do we NEED for how many RPM?

quick 'fag packet' calculation -
@lalalandrus wants 30kph -> 30000m/h =>500m/min -> 8.3m/s -> 8300 mm/s
we have a hall change every ~6mm => ~1380 hall clicks/s
So if we run at 8khz, we have ~6 interrupts per hall tick.
Is this enough for a rough sin wave?  Probably?
At 40kph -> ~4 interrupts per hall tick -> probaly still good enough.  Although at that speed, who's going to hear the noise?

**Comment by lalalandrus** [comment]
> @EmanuelFeru - so your position estimation does not depend on a time interval, as long as we're within a range?
> We could easily test at 8khz on STM32 by only running the BLDC every 2nd interrupt? (please test?)
> How fast do we NEED for how many RPM?
> 
> quick 'fag packet' calculation -
> @lalalandrus wants 30kph -> 30000m/h =>500m/min -> 8.3m/s -> 8300 mm/s
> we have a hall change every ~6mm => ~1380 hall clicks/s
> So if we run at 8khz, we have ~6 interrupts per hall tick.
> Is this enough for a rough sin wave? Probably?
> At 40kph -> ~4 interrupts per hall tick -> probaly still good enough. Although at that speed, who's going to hear the noise?
> :) :)

but your butt will feel it travel up your spine into your ear.... :D

**Comment by EmanuelFeru** [comment]
Than should be still ok. Not as smooth and quiet as for 16kHz but still better than Commutation method.
And indeed, at that speed I think the road noise will cover anyway the motor noise.

**Comment by lalalandrus** [comment]
@EmanuelFeru if we cant get the STM32F103 to work we can migrate to STM32F405/415
https://www.digikey.com/product-detail/en/stmicroelectronics/STM32F415RGT6/497-11907-ND/2757675
https://www.digikey.com/product-detail/en/stmicroelectronics/STM32F405RGT7/497-17433-ND/5051343

**Comment by EmanuelFeru** [comment]
@lalalandrus yes, that can be. I have now much better skills in desoldering these types of SMD components :) The only issue is for other people that want to use the code and cannot desolder, not having the micro-controller, etc.

**Comment by btsimonh** [comment]
@ 8khz on GD32:
Main loop interval_us 5000; lates 2, processing_us 724, interval by tick 5, bldc freq 16035
last measurements (16khz):
Main loop interval_us 5000; lates 1, processing_us 1341, interval by tick 5, bldc freq 16005
first measurement (no inline):
Main loop interval_us 5001; lates 3, processing_us 1955, interval by tick 5, bldc freq 16020 
Original firmware:
Main loop interval_us 5000; lates 3, processing_us 465, interval by tick 5, bldc freq 16055

I think 8khz should be good with STM32F1, it's not far off where we were.
I believe there is optimisation in @EmanuelFeru 's auto generated code to be had, but not something I fancy looking at tonight :).
8khz pushed in this repo on my newbldc-btsimonh branch.
(still want to instrument in CPU cycles, so we can measure the actual interrupt routines... but done for today!)

@EmanuelFeru - fantastic work! @lalalandrus - thanks for the first integration (well, the one i chose...).

I do want to think about how we can drive the sinusoidal waveforms statically at an angle and power for very slow speed use & slow start.  It hurts my brain, so suggestion welcome.  (I'd like to be able to specify posn (hall count from hall interrupts) fractional posn, and 'power', and for the system to set the wheels to this posn, maintaining the specified power (current) into the coils to keep it there.)

@lalalandrus - this repo *must* have options to work on the lowest power devices; basically you should be able to take any HB and use the firmware.  Not saying we can't have extra features that depend on a more powerful platform.... :)

**Comment by btsimonh** [comment]
@EmanuelFeru - "When you have some repo to share, I would like to try to see how motors are behaving... but you have a GD32 board.. hmm"
it's here :).  currently @8khz.  should just build for STM32, no changes except performance.
https://github.com/bipropellant/bipropellant-hoverboard-firmware/tree/newbldc-btsimonh

would be good to see your output from the main timing diags....
on serial, type
\n
unlockASCII\n
s\n
(run the HB by double tapping a side)
then
s\n
a second time to check it's consistent.

**Comment by lalalandrus** [comment]
excited to test. it is amazing what we have accomplished in just over 2 weeks

**Comment by EmanuelFeru** [comment]
@btsimonh Thank you as well for your effort!

One remark, you mentioned some ticks, Do you use any sort of filter in your control algorithm before sending the commands to motor control?
Because I just tried with no filtering on Potentiometers and I do get ticks, and those I think are coming from very sudden commands.
I do get them also in the Commutation method but it feels less, because the motors already make quite some noise.

I will take a brake now, let's resume it soon. Nice Work!

**Comment by EmanuelFeru** [comment]
@btsimonh 
https://github.com/bipropellant/bipropellant-hoverboard-firmware/tree/newbldc-btsimonh
is locked.. I think

**Comment by btsimonh** [comment]
hmm..  you should be able to get there by just selecting the branch dropdown from the main repo...
or add it as a remote you yours (if based on ours), and merge to a branch of your own.
or clone the base repo, do a full fetch, then checkout newbldc-btsimonh.
I use 'sourcetree' - not perfect but an OK git UI for windows....

**Comment by lalalandrus** [comment]
The code works and I hit 30km exactly under load. A couple things I observed were sounds from the motor when under load and when it starts phase advance. When underload it almost seems like it is skipping steps.

**Comment by btsimonh** [comment]
it's very easy to reproduce close to or at zero velocity, but this is not unexpected.
An article on it
https://www.machinedesign.com/motorsdrives/why-open-loop-steppers-lose-steps-and-how-solve-problem
I should stress that I had the exact same ticking or missing with the original code, but it was less severe near zero speed, and less often generally. (I had put it down to sensor mireads, but now I have these producing a console log, they do not necessarily correlate, and I also ignore the data when they happen)

P.s. we should move to a new issue - else we'll break github by quantity of comments!
created one to continue on here:
https://github.com/bipropellant/bipropellant-hoverboard-firmware/issues/32
